### PR TITLE
Fix settings, enable enterprise, and format

### LINKED ISSUE #144: Limited to 30 gists
Regardless of the value under **max_gists**, the limit of gists fetched is 30. Could you please advise?

### LINKED ISSUE #148: (Enterprise) Gist: GitHub returned error 401: Bad credentials
My settings are:  

```
{
    "token": "***",
    "enterprise": true,
    "url": "https://github.***.ru",
}
```

Every time I try to create gist I get "Gist: GitHub returned error 401: Bad credentials" . Changing url to "https://api.github.***.ru" doesn't solve the problem. Token is okay, I checked it with simple curl request to API.

### PR DESCRIPTION
**Pull request by vmuriart**
Fixes #148 #51 (Enterprise)
Fixes #144 (max_gist). different approach than #171 in order to also close the enterprise issue.
Incorporates pr #159, #160, 
Cleaned up formatting and whitespacing similar to #172 for travis test.
Removed subl2 support to significantly clean-up code
Removed unused(?) curl fetch.

### CODE REVIEW

**Comment by bertrandom** [comment]
I just spent 30 minutes trying to configure Gist with my work's Github Enterprise with no luck until I found this PR. @condemil, would you consider merging this in?

**Comment by Saborknight** [comment]
@vmuriart Could you consider adding your commit https://github.com/vmuriart/Gist/commit/73b5b97dc64ab36f41f9dcbe65d922ce8d4df85c to this to solve the AttributeError when calling Github for authors for the issue #151 to allow this feature to be re-enabled, as you stated in your commit? THANKS!

**Comment by vmuriart** [comment]
@Saborknight I had forgotten that this `pr` existed. Looking back to this, I should have broken it down into smaller pull requests to keep changes atomic.

**Comment by skylock** [comment]
Thank you for the fix !

**Comment by qkdreyer** [comment]
Thanks for the fixes :)

**Pull request merged**
